### ISSUE TITLE
InvalidRequestError: This model's maximum context length is 16385 tokens. However, your messages resulted in 16394 tokens. Please reduce the length of the messages.

### ISSUE THREAD

**Issue by pleabargain** [mshumer/gpt-author#2]
How do I set the tokens so that I don't get this error?
I was at chapter 17 of 20 when the script died.

**Comment by pogic** [comment]
write less chapters, or upgrade the gpt-4 model you're using

**Comment by pleabargain** [comment]
> write less chapters, or upgrade the gpt-4 model you're using

I don't have access to GPT4 :(
I reduced the chapter number and I got an epub. Thanks.
