### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by kyoesu** [mshumer/gpt-author#30]
```
 in generate_text(prompt, model, max_tokens, temperature)
     20     response = requests.post("https://api.anthropic.com/v1/messages", headers=headers, json=data)
     21     print (response)
---> 22     response_text = response.json()['content'][0]['text']
     23     return response_text.strip()
     24 

KeyError: 'content'
```

 400 error pops up in the generate_text function in the request

**Comment by chunhualiao** [comment]
I got the same error.

**Comment by chunhualiao** [comment]
> I got the same error.

Oh. I used a wrong api key. The problem is solved now.

**Comment by kyoesu** [comment]
I found the problem. I don't have the money.

{"type":"error","error":{"type":"invalid_request_error","message":"Your credit balance is too low to access the Claude API. Please go to Plans & Billing to upgrade or purchase credits."}}
