### ISSUE TITLE
anthropic cost

### ISSUE THREAD

**Issue by Alakirhell** [mshumer/gpt-author#36]
hi, I have a question, does antrophic need $5 to make it work?

**Comment by DonHanson** [comment]
Anthropoc gives you a $5 credit for free account but that has a super low rate limit. If you pay $5 or more then get a higher rate limit for creating longer books.

**Comment by Alakirhell** [comment]
> Anthropoc gives you a $5 credit for free account but that has a super low rate limit. If you pay $5 or more then get a higher rate limit for creating longer books.

and did you get to write a book?
