### ISSUE TITLE
Writing Style

### ISSUE THREAD

**Issue by wyiywmim** [mshumer/gpt-author#9]
Hi, 
this is such a great tool, thank you for sharing!

I'm not in development and just use trial and error to figure things out here... It works well so far. 
I tried to change the style "fantasy" and replaced it anywhere it shows up with other writing styles but it somehow keeps writing fantasy style. I guess the style is implemented somewhere 'deeper' (sorry, I'm lacking programming terms). 
Is there a way to make the style open to change? 
If this is not in your intention with this tool please ignore.
Thanks, 
Tina

**Comment by snip3r009** [comment]
Hi Tina,
Wat version do you use at this moment? 
The edited version, you can put in any genre.

**Comment by wyiywmim** [comment]
I see :) 
I copied it yesterday but it's all new already. Speedy!
thanks, I'll try the updated version.

**Comment by wyiywmim** [comment]
It uses the style I put in -present tense and first person- in the first chapter but drops it in the following chapters, somehow it ignores the style there. 
But I use 3.5. Maybe 4 is better... (when I can get it)

**Comment by snip3r009** [comment]
try to generate a better prompt

**Comment by wyiywmim** [comment]
Can it still be a prompt issue on my side when it works well in the first chapter?
